### ISSUE TITLE
Image for entity?

### ISSUE THREAD

**Issue by jackyaz** [rodpayne/home-assistant_person_location#3]
Not an issue as such, but more of a question. Is there any way to associate an image with the created entity? I'm using the device_tracker platform option. I've tried the customisation via configuration.yaml which works for an entity created by another integration, but doesn't seem to be working for this one.

**Comment by rodpayne** [comment]
Could you give me an example of what is done in `configuration.yaml` for the other integration?

**Comment by jackyaz** [comment]
So the only other entity I've set a picture for is the mobile app, like so:
```
homeassistant:
  customize:
    device_tracker.s21ultra_mobileapp:
      entity_picture: /local/icons/jack.jpg
    device_tracker.jack_location:
      entity_picture: /local/icons/jack.jpg
```
I tried re-using the same syntax for the tracker created by this project but doesn't work
