### ISSUE TITLE
Integration is only working with first entry in person_names ?

### ISSUE THREAD

**Issue by Kilowatt-W** [rodpayne/home-assistant_person_location#7]
Hi there,

i used your addon integration for some time and was really happy with it.

Since some days (I think with one of the latest updates) only the first entry in person_names gets some sensors and is alive after reboot. The second is ignored and not generated ?

When i swap entries the other first gets evaluated ?

Maybe there is an error since the new updates ?

```
person_location:
  mapbox_api_key: !#secret_mapbox
  osm_api_key: !#secret_osm
  google_api_key: !#secret_google_api_key
  language: de
  region: EU
  follow_person_integration: true
  create_sensors: "direction, geocoded, altitude, meters_from_home"  
  person_names:
    - name: Wife
      devices:
        - person.susi
    - name: Husband
      devices: 
        - person.max
```

Greetings from Austria

Kilowatt
